### ISSUE TITLE
BUG: Fail to compile on Kali

### ISSUE THREAD

**Issue by royharoush** [RoliSoft/Host-Scanner#1]
Hi,
When trying to compile i get the following error.
```

/root/Host-Scanner/Utils.cpp:5:40: fatal error: boost/core/ignore_unused.hpp: No such file or directory
 #include <boost/core/ignore_unused.hpp>
                                        ^
compilation terminated.
CMakeFiles/HostScanner.dir/build.make:330: recipe for target 'CMakeFiles/HostScanner.dir/Utils.cpp.o' failed
make[2]: *** [CMakeFiles/HostScanner.dir/Utils.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/HostScanner.dir/all' failed
make[1]: *** [CMakeFiles/HostScanner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

followed the debian\ubuntu\kali instructions. 
What did i do wrong   ? 
Thanks,
Roy

**Comment by RoliSoft** [comment]
Which version of Kali are you using? 1, 2 or rolling?

The `ignore_unused.hpp` file was added in boost 1.56, while if I recall correctly, Kali 2 only has boost 1.55.

If on rolling, try explicitly installing the newer version, as the `libboost-all-dev` metapackage may refer to an older one:

    apt-get install libboost1.60-all-dev

You will also need to install Go for the other repository, in order to get fresh vulnerability data. The application is currently under heavy development, and as such, unfortunately this process hasn't been streamlined yet.

**Comment by RoliSoft** [comment]
Due to the lack of any progress on this issue, I'm closing it.

If it did not solve your issue, or you found a new one, feel free to open a new ticket.
